name: terraform_security_checks

on:
  workflow_call:
    inputs:   
      job_name:
        required: true
        type: string
        default: 'Terraform Security and Compliance Checks'
      runs_on:
        required: true
        type: string
        default: 'ubuntu-latest'
      working_directory:
          required: true
          type: string

jobs:
  terraform_security_checks:
    name: ${{ inputs.job_name }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: tflint setup
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: latest

      - name: trivy setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: latest

      - name: tflint scan
        id: tflint
        run: tflint --init && tflint
        working-directory: ${{ inputs.working_directory }}
        continue-on-error: true

      - name: trivy scan
        run: |
          trivy config . --tf-vars terraform.tfvars \
            --severity HIGH,CRITICAL --exit-code 1 \
            --format table
        working-directory: ${{ inputs.working_directory }}
        continue-on-error: true

      - name: tfsec scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          version: latest
          working_directory: ${{ inputs.working_directory }}
          additional_args: --tfvars-file=${{ inputs.working_directory }}/terraform.tfvars
          soft_fail: true

      - name: checkov scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.working_directory }}
          framework: terraform
          var_file: terraform.tfvars
          output_format: cli
          soft_fail: true
